---
- name: Deploy pozos application
  gather_facts: No
  hosts: App_Server
  become: true
  
  tasks:
# STOP BOTH CONTAINERS BEFORE DEPLOYING FLASK UPDATE
#===================================================
  - name: Stop flask container
    docker_container:
      name: flask
      state: stopped

  - name: Stop website container
    docker_container:
      name: website
      state: stopped
  
# CREATE NEW FLASK CONTAINER USING REGISTRY IMAGE
#================================================
  - name: create flask container
    docker_container:
      insecure_registry: true
      name: flask
      image: 192.168.1.49:flask:${BUILD_ID}
      pull: always
      state: started
      ports:
        - "5000:5000"

# DEPLOY WEBSITE CONTAINER
#=========================
#  - name: Create website container
#    docker_image:
#      build:
#        path: ./
#      name: website



   # command: docker build -t website ./website
    #file:
     # path: ./Dockerfile
      #  state: directory
       # owner: root
        #group: root
        #mode: '0755'

