---
- name: Deploy pozos application
  gather_facts: No
  hosts: App_Server
  become: true
  
  tasks:
# STOP BOTH CONTAINERS BEFORE DEPLOYING FLASK UPDATE
#===================================================
  - name: Stop flask container
    docker_container:
      name: flask
      state: stopped

  - name: Stop website container
    docker_container:
      name: website
      state: stopped
  
# CREATE NEW FLASK CONTAINER USING REGISTRY IMAGE
#================================================
  - name: create flask container
    docker_container:
      name: flask
      image: 192.168.1.49:5000/flask_{{ IMAGE_BUILD_ID }}
      state: started
      ports:
        - "5000:5000"

# REMOVE OLD APP_SERVER DIRECTORY IN LOCAL SERVER
#================================================
  - name: remove app_server directory
    file:
      path: /4DVOP_POZOS/App_Server
      state: absent

# CLONE GIT > RECCUPERATION DU DOCKERFILE
#========================================
  - name: Git clone repo App_Server
    ansible.builtin.git:
      repo: https://192.168.1.48/pozos/pozos.git
      dest: /4DVOP_POZOS/
      #separate_git_dir: /src/ansible-examples.git


# DEPLOY WEBSITE CONTAINER
#=========================
  - name: Create website container
    docker_image:
      build: 
        path: /4DVOP_POZOS/App_Server/website/
        source: build
      name: website
      state: started



   # command: docker build -t website ./website
    #file:
     # path: ./Dockerfile
      #  state: directory
       # owner: root
        #group: root
        #mode: '0755'

