---
- name: Deploy pozos application
  gather_facts: No
  hosts: App_Server
  #become: yes
  #become_method: sudo
  
  tasks:
# STOP BOTH CONTAINERS BEFORE DEPLOYING FLASK UPDATE
#===================================================
  - name: Stop flask container
    docker_container:
      name: flask
      state: absent
    ignore_errors: yes

  - name: Stop website container
    docker_container:
      name: website
      state: absent
    ignore_errors: yes

# CREATE NEW FLASK CONTAINER USING REGISTRY IMAGE
#================================================
  - name: create flask container
    docker_container:
      name: flask
      image: 192.168.1.49:5000/flask_{{ IMAGE_BUILD_ID }}
      state: started
      restart_policy: always
      ports:
        - "5000:5000"

# COPY GITLAB REPO TO PRODUCTION SERVER
#=======================================
  - name: Clone a private repository into production server
    git:
      repo: git@192.168.1.48:pozos/pozos.git
      version: master
      dest: /pozos
      accept_hostkey: yes

# BUILD WEBSITE CONTAINER
#=========================
  - name: Build website container
    command: "docker build -t website /pozos/website"

# RUN  WEBSITE CONTAINER
#=======================
  - name: Run website container
    command: "docker run --name website --link flask --restart always --env USERNAME=toto --env PASSWORD=python -d -p 8080:80 website"

# BUILD WEBSITE CONTAINER
#=========================
#  - name: Build website container
#    docker_image:
#      name: website
#      build: 
#        path: /pozos/website
#      source: build
#      state: present

# RUN  WEBSITE CONTAINER
#=======================
#  - name: Run website container
#    docker_container:
#      name: website
#      state: started
#      links: 
#        - "flask"
#      ports: 
#        - "80:80"