---
- name: Deploy pozos application
  gather_facts: No
  hosts: App_Server
  become: true
  
  tasks:
# STOP BOTH CONTAINERS BEFORE DEPLOYING FLASK UPDATE
#===================================================
  - name: Stop flask container
    docker_container:
      name: flask
      state: stopped

  - name: Stop website container
    docker_container:
      name: website
      state: stopped
  
# CREATE NEW FLASK CONTAINER USING REGISTRY IMAGE
#================================================
  - name: create flask container
    docker_container:
      name: flask
      image: 192.168.1.49:5000/flask_{{ IMAGE_BUILD_ID }}
      state: started
      ports:
        - "5000:5000"

# CLONE GIT > RECCUPERATION DU DOCKERFILE
#========================================
  - name: Git clone repo App_Server
    git:
      repo: https://192.168.1.48/pozos/pozos.git
      dest: ./pozos
      force: yes

# DEPLOY WEBSITE CONTAINER
#=========================
  - name: Create website container
    docker_image:
      build: 
        path: ./pozos/website/
        source: build
      name: website
      state: started



   # command: docker build -t website ./website
    #file:
     # path: ./Dockerfile
      #  state: directory
       # owner: root
        #group: root
        #mode: '0755'

