version: '3'
services:
#=============================================
#=========================CONTAINER PHP-APACHE
#=============================================
  php-apache:
    container_name: website
    restart: always
    build: ./website
    ports:
      - "8080:80"
    networks: 
      - studentlist_network
    depends_on:
      - "flask"
    environment:
      - USERNAME=toto
      - PASSWORD=python

#=============================================
#==============================CONTAINER FLASK
#=============================================
  flask:
    container_name: flask
    restart: always
    build: ./simple_api
    networks: 
      - studentlist_network

#=============================================
#==============================NETWORK SETTING
#=============================================
networks:
  studentlist_network:


